version: "3"

services:
    backend:
        container_name: backend_nodejs
        build: ./nodejs
        ports:
            - "5000:5000"
        networks:
            - dev-network


networks:
    dev-network:
