version: "3"

services:
  backend:
    container_name: backend_java
    build: ./backend/jpay.customers.service
    ports:
      - "8080:8080"
    networks:
      - dev-network
  frontend:
    container_name: frontend_angular
    build: ./frontend/CustomersClient
    ports:
      - "4200:80"
    networks:
      - dev-network

networks:
  dev-network: