version: "3"

services:
    backend:
        container_name: backend_java
        build: ./backend
        ports:
            - "5000:5000"
        networks:
            - dev-network


networks:
    dev-network:
