version: "3"

services:
    backend:
        container_name: backend_java
        build: ./backend/jpay.customers.service
        ports:
            - "8080:8080"
        networks:
            - dev-network


networks:
    dev-network:
